In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
import pandas as pd
import json


with open('/content/drive/My Drive/Procesamiento de Datos/Parcial/season_stats.json') as file:
    json_data = json.load(file)
teams_list = []
aggregate_stats_list = []
players_list = []

for match_id, teams in json_data.items():
    for team_id, team_info in teams.items():
        team_details = team_info['team_details']
        team_details['match_id'] = match_id
        team_details['team_id'] = team_id
        teams_list.append(team_details)
        aggregate_stats = team_info['aggregate_stats']
        aggregate_stats['match_id'] = match_id
        aggregate_stats['team_id'] = team_id
        aggregate_stats_list.append(aggregate_stats)
        for player_name, player_info in team_info['Player_stats'].items():
            player_stats = player_info['Match_stats']
            player_stats.update(player_info['player_details'])
            player_stats['match_id'] = match_id
            player_stats['team_id'] = team_id
            player_stats['player_name'] = player_name
            players_list.append(player_stats)

df_team_details = pd.DataFrame(teams_list)
df_aggregate_stats = pd.DataFrame(aggregate_stats_list)
df_player_stats = pd.DataFrame(players_list)

In [15]:
df_teams

    team_id          team_name       team_rating        date match_id
0       166       Huddersfield              6.14  30/01/2018  1190418
1        26          Liverpool  7.22285714285714  30/01/2018  1190418
2       211           Brighton  7.15384615384615  01/01/2018  1190424
3       183        Bournemouth  6.90285714285714  01/01/2018  1190424
4        15            Chelsea  6.77142857142857  13/01/2018  1190342
..      ...                ...               ...         ...      ...
755      27            Watford  6.17071428571429  11/03/2018  1190373
756      32  Manchester United  7.31928571428571  03/02/2018  1190367
757     166       Huddersfield  6.40857142857143  03/02/2018  1190367
758      96              Stoke  6.31076923076923  12/03/2018  1190401
759     167    Manchester City  7.23769230769231  12/03/2018  1190401

[760 rows x 5 columns]

In [16]:
df_aggregate_stats

,won_corners,att_sv_low_centre,won_contest,total_tackle,aerial_lost,possession_percentage,accurate_pass,total_pass,total_throws,shot_off_target,...,att_sv_high_right,att_sv_low_right,att_sv_high_left,att_miss_high_left,att_goal_high_right,att_goal_high_left,att_post_right,att_goal_high_centre,penalty_save,att_post_high
0,1,1,5,11,15,25.3,214,308,15,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,2,6,13,16,74.7,809,913,24,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,1,12,23,16,49.1,300,394,21,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12,3,17,6,25,50.9,329,403,19,5,...,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,1,15,13,18,55.4,426,508,21,4,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,9,1,7,13,22,40.3,245,324,28,5,...,NaN,3,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
756,5,3,27,15,18,74.3,697,786,23,4,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
757,2,NaN,4,22,14,25.7,190,265,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
758,3,NaN,9,19,16,22.9,165,245,25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
759,10,1,10,16,13,77.1,762,847,20,8,...,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_players

,good_high_claim,touches,saves,total_pass,formation_place,accurate_pass,player_id,player_name,player_position_value,player_position_info,...,post_scoring_att,second_yellow,red_card,clearance_off_line,own_goals,last_man_tackle,att_pen_target,penalty_save,att_pen_miss,att_pen_post
0,2,39,4,28,1,11,131171,Jonas LÃ¶ssl,1,GK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,30,NaN,20,4,16,109117,Terence Kongolo,2,DC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,38,NaN,15,3,6,101664,Chris LÃ¶we,2,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,44,NaN,28,6,27,29026,Zanka,2,DC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,46,NaN,27,5,21,132360,Christopher Schindler,2,DC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13670,NaN,NaN,NaN,NaN,0,NaN,14053,Yaya TourÃ©,5,Sub,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13671,NaN,NaN,NaN,NaN,0,NaN,14199,Claudio Bravo,5,Sub,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13672,NaN,NaN,NaN,NaN,0,NaN,101374,John Stones,5,Sub,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13673,NaN,NaN,NaN,NaN,0,NaN,88300,Danilo,5,Sub,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13674,NaN,9,NaN,8,0,8,77464,Ilkay GÃ¼ndogan,5,Sub,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
team_details_filtered = df_team_details[(df_team_details['match_id'] == '1190418') &
                                        (df_team_details['team_id'] == '166')]


aggregate_stats_filtered = df_aggregate_stats[(df_aggregate_stats['match_id'] == '1190418') &
                                              (df_aggregate_stats['team_id'] == '166')]
player_stats_filtered = df_player_stats[(df_player_stats['match_id'] == '1190418') &
                                        (df_player_stats['team_id'] == '166')]


print("\nPlayer Stats for team_id 166 and match_id 1190418:")
print(player_stats_filtered)

Player Stats for team_id 166 and match_id 1190418:
   good_high_claim touches saves total_pass formation_place accurate_pass  \
0                2      39     4         28               1            11
1              NaN      30   NaN         20               4            16
2              NaN      38   NaN         15               3             6
3              NaN      44   NaN         28               6            27
4              NaN      46   NaN         27               5            21
5              NaN      54   NaN         27               2            15
6              NaN      44   NaN         30              11            26
7              NaN      47   NaN         36               7            27
8              NaN      53   NaN         43               8            31
9              NaN      40   NaN         25              10            14
10             NaN      16   NaN          9               9             6
11             NaN     NaN   NaN        NaN               0           NaN
12             NaN      13   NaN         10               0             7
13             NaN       9   NaN          5               0             4
14             NaN     NaN   NaN        NaN               0           NaN
15             NaN     NaN   NaN        NaN               0           NaN
16             NaN     NaN   NaN        NaN               0           NaN
17             NaN      12   NaN          5               0             3

   player_id            player_name player_position_value  \
0     131171            Jonas LÃ¶ssl                     1
1     109117        Terence Kongolo                     2
2     101664             Chris LÃ¶we                     2
3      29026                  Zanka                     2
4     132360  Christopher Schindler                     2
5     136896    Florent Hadergjonaj                     2
6     145277         Philip Billing                     3
7     318153             Aaron Mooy                     3
8      82593          Jonathan Hogg                     3
9     106880       Laurent Depoitre                     4
10    135259           Steve Mounie                     4
11    135837            Tommy Smith                     5
12     90996          Collin Quaner                     5
13     42947     Rajiv van La Parra                     5
14    104035         Michael Hefele                     5
15    135179           Joel Coleman                     5
16    107848         Alex Pritchard                     5
17     90918               Tom Ince                     5

   player_position_info  ... post_scoring_att second_yellow red_card  \
0                    GK  ...              NaN           NaN      NaN
1                    DC  ...              NaN           NaN      NaN
2                    DL  ...              NaN           NaN      NaN
3                    DC  ...              NaN           NaN      NaN
4                    DC  ...              NaN           NaN      NaN
5                    DR  ...              NaN           NaN      NaN
6                    MC  ...              NaN           NaN      NaN
7                    MC  ...              NaN           NaN      NaN
8                    MC  ...              NaN           NaN      NaN
9                    FW  ...              NaN           NaN      NaN
10                   FW  ...              NaN           NaN      NaN
11                  Sub  ...              NaN           NaN      NaN
12                  Sub  ...              NaN           NaN      NaN
13                  Sub  ...              NaN           NaN      NaN
14                  Sub  ...              NaN           NaN      NaN
15                  Sub  ...              NaN           NaN      NaN
16                  Sub  ...              NaN           NaN      NaN
17                  Sub  ...              NaN           NaN      NaN

   clearance_off_line own_goals last_man_tackle att_pen_target penalty_save  \
0                 NaN       NaN             NaN            NaN          NaN
1                 NaN       NaN             NaN            NaN          NaN
2                 NaN       NaN             NaN            NaN          NaN
3                 NaN       NaN             NaN            NaN          NaN
4                 NaN       NaN             NaN            NaN          NaN
5                 NaN       NaN             NaN            NaN          NaN
6                 NaN       NaN             NaN            NaN          NaN
7                 NaN       NaN             NaN            NaN          NaN
8                 NaN       NaN             NaN            NaN          NaN
9                 NaN       NaN             NaN            NaN          NaN
10                NaN       NaN             NaN            NaN          NaN
11                NaN       NaN             NaN            NaN          NaN
12                NaN       NaN             NaN            NaN          NaN
13                NaN       NaN             NaN            NaN          NaN
14                NaN       NaN             NaN            NaN          NaN
15                NaN       NaN             NaN            NaN          NaN
16                NaN       NaN             NaN            NaN          NaN
17                NaN       NaN             NaN            NaN          NaN

   att_pen_miss att_pen_post
0           NaN          NaN
1           NaN          NaN
2           NaN          NaN
3           NaN          NaN
4           NaN          NaN
5           NaN          NaN
6           NaN          NaN
7           NaN          NaN
8           NaN          NaN
9           NaN          NaN
10          NaN          NaN
11          NaN          NaN
12          NaN          NaN
13          NaN          NaN
14          NaN          NaN
15          NaN          NaN
16          NaN          NaN
17          NaN          NaN

[18 rows x 38 columns]

In [23]:
df_team_details.to_csv("Team details")
df_aggregate_stats.to_csv("Stats_of_the_match")
df_player_stats.to_csv("Player_stats")